train:
  batch_size: 32
  num_workers: 16
  datasets:
    - _target_: source.datasets.classic.LibrispeechDataset
      part: dev-other
      max_audio_length: 17.0
      max_text_length: 270
      text_encoder: source.text_encoder.ctc_char_text_encoder.CTCCharTextEncoder
      log_spec: True
      wave_augs:
      spec_augs:

    #- _target_: source.datasets.classic.LibrispeechDataset
    #  part: train-other-500
    #  max_audio_length: 17.0
    #  max_text_length: 270
    #  text_encoder: source.text_encoder.ctc_char_text_encoder.CTCCharTextEncoder
    #  log_spec: True
    #  wave_augs:
    #  spec_augs:



test:
  batch_size: 16
  num_workers: 16
  datasets:
    - _target_: source.datasets.classic.LibrispeechDataset
      part: test-other
      limit: 1500
      text_encoder: source.text_encoder.ctc_char_text_encoder.CTCCharTextEncoder