defaults:
  - arch: model_conf
# - augmentations: aug
  - dataset: libri
  - loss: loss_conf
  - scheduler: scheduler_conf
  - metrics: metrics_conf
  - preprocessing: preprocessing_conf
  - trainer: trainer_conf
  - optimizer: optimizer_conf

name: deep_speech_2
n_gpu: 1
checkpoint: