defaults:
  - gen: gen_conf
  - disc: disc_conf
  - dataset: data
  - loss: loss_conf
  - mel: mel_conf
  - scheduler_g: scheduler_g_conf
  - scheduler_d: scheduler_d_conf
  - trainer: trainer_conf
  - optimizer_g: optimizer_g_conf
  - optimizer_d: optimizer_d_conf

name: vits
n_gpu: 1
checkpoint: