epochs: 200
save_dir: "$ROOT/saved/cascaded"
save_period: 1
verbosity: 2
early_stop: 65
visualize: wandb
wandb_project: cascaded
len_epoch:
log_step:
grad_norm_clip: 10
beam_size: 5
accum_step: 1
eval_interval: 1
resume: "$ROOT/pretrained/cascaded/baseline.pth"
from_pretrained: True