- _target_: torchmetrics.ScaleInvariantSignalNoiseRatio
  name: SI-SNR Metric

- _target_: torchmetrics.SignalNoiseRatio
  name: SNR Metric

#- _target_: source.metric.bsrnn.SafeSignalDistortionRatio
#  name: SDR Metric