epochs: 300
save_dir: "$ROOT/saved/vits"
save_period: 5
eval_interval: 1
verbosity: 2
early_stop: 65
visualize: wandb
wandb_project: vits
len_epoch:
log_step:
grad_norm_clip: 10
beam_size: 5
accum_step: 2
c_stft: 9
c_mel: 1.
c_kl: 0.2
resume: "$ROOT/checkpoints/vits/pretrained.pth"
from_pretrained: True