training_files: "/home/comp/Рабочий стол/Mashup/files/train3.txt"
validation_files: "/home/comp/Рабочий стол/Mashup/files/valid3.txt"
segment_size: 8000
max_wav_value: 32768.0
sampling_rate: 32000
filter_length: 1024
hop_length: 320
win_length: 1024
mel_channels: 100
mel_fmin: 50.0
mel_fmax: 16000.0
batch_size: 2