training_files: "$ROOT/files_pg/train2.txt"
validation_files: "$ROOT/files_pg/valid2.txt"
# training_files: "$ROOT/files_pg/train_gc.txt"
# validation_files: "$ROOT/files_pg/valid_gc.txt"
segment_size: 8000
max_wav_value: 32768.0
sampling_rate: 32000
filter_length: 1024
hop_length: 320
win_length: 1024
mel_channels: 100
mel_fmin: 50.0
mel_fmax: 16000.0
batch_size: 2
#batch_size: 8